### ISSUE TITLE
1.10.1 Kopernicus could not load planetary system

### ISSUE THREAD

**Issue by Fisheiyy** [R-T-B/Kopernicus#43]
Hello, I am back again yes I am getting the same error as before and have no clue I have removed everything that had miniavc and still getting the error.
[Kopernicus Issue Logs.zip](https://github.com/R-T-B/Kopernicus/files/5682486/Kopernicus.Issue.Logs.zip)

**Comment by R-T-B** [comment]
Sorry for the slow response, I've been overwhelmed with worth the past few days.  I will take another look at this shortly, I am dealing with 1.11's launch.

Just wanted you to know not forgotten.

**Comment by Fisheiyy** [comment]
been checking this daily waiting 1.11 looks really enticing.

**Comment by R-T-B** [comment]
We will have support for 1.11 nearly within the hour, but may be buggy.  Looking at your logs now.

**Comment by R-T-B** [comment]
So, your log files suggest no errors from Kopernicus itself.  Can you list what third party mods you have?

The most common errors like this are from out of date solar panel mods that interact badly with Kopernicus multistar support.  If you have only one star present and do not need multistar support, you can get around this by deleting GameData/Kopernicus/Config/SolarPanels.cfg.

That makes the game use stock solar code, which is more mod friendly but only supports one star.

**Comment by Fisheiyy** [comment]
I have around 50 mods I think from clan and curse I can screenshot the names if you want though its kinda hard with remote desktop because I'm currently not hone

**Comment by R-T-B** [comment]
I can wait or you can send the screenshot of gamedata whenever is convienient.

**Comment by Fisheiyy** [comment]
https://gyazo.com/9d4ee66189ab7c62a03f7a22d383fb7f https://gyazo.com/acc5cbc3461dec34cc44789970d7df9f https://gyazo.com/6aa57ce23ee94de984157fc3ac4cf0a5 https://gyazo.com/e05507eae013b8c76e2bec57b5186a32 https://gyazo.com/f13e88379a854f2f106f13b5b6c5e0f9 https://gyazo.com/9dad144b5089d214f8bc0876a0465d1d

**Comment by R-T-B** [comment]
Great, it'll take a tiny bit to research each mod, but I'm on it.

**Comment by Fisheiyy** [comment]
> Great, it'll take a tiny bit to research each mod, but I'm on it.
> 
> EDIT: Right off the bat, you have a GameData folder inside your primary GameData. This is likely your issue. Anything inside this "sub-GameData" should be in the main gamedata, not a subdirectory like that.

i always drag the stuff out of it this is whats in it https://gyazo.com/8ec9e56abd20fb68e4fcf3292fd6dfbd

**Comment by Fisheiyy** [comment]
[Kopernicus Issue Logs.zip](https://github.com/R-T-B/Kopernicus/files/5712677/Kopernicus.Issue.Logs.zip)
some new files and a screenshot of what it told me https://gyazo.com/aa35f51fabbcd5940a5164a7b2ed948f

**Comment by R-T-B** [comment]
Try moving those into the main gamedata, and deleting GameData/Kopernicus/Config/SolarPanels.cfg

Unless you have more than one star in your system, of course.  Then we'll have to try a difference approach.

**Comment by R-T-B** [comment]
Also, try deleting KSP.log before your next run (in install root).  It's not really needed, but it's nearly 300MBs of dead log data, and it will only slow your game down...  hehe.

**Comment by Fisheiyy** [comment]
im just loading kop by itself right now i want to play the beyond home mod which has 2 suns so https://forum.kerbalspaceprogram.com/index.php?/topic/182708-191-110x-beyond-home-150-supports-parallax/ scroll down and you will see the deltav map

**Comment by R-T-B** [comment]
ah, yeah then don't delete that file.

Hmmm.  You just have it by itself?  And it still does not load?

Tell you what.  Try deleting <Install root>/KSP.log, running the game to regenerate that file, and post the result.  I want to see if maybe it's out of date and I'm getting old data or something.

**Comment by Fisheiyy** [comment]
waiting for ksp to load and will give a new ksp.log

**Comment by Fisheiyy** [comment]
it takes like 15 mins

**Comment by Fisheiyy** [comment]
[KSP.zip](https://github.com/R-T-B/Kopernicus/files/5712994/KSP.zip)
okay got the new log file its a zip because its over the file limit for github

**Comment by R-T-B** [comment]
`[LOG 18:48:30.235] KSP-AVC -> System.ArgumentException: Getting control 0's position in a group with only 0 controls when doing repaint
Aborting
  at UnityEngine.GUILayoutGroup.GetNext () [0x000a2] in <fa6f9762ac624af092525d37c9d516c4>:0 
  at UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type layoutType) [0x00050] in <fa6f9762ac624af092525d37c9d516c4>:0 
  at UnityEngine.GUILayout.BeginHorizontal (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) [0x00001] in <fa6f9762ac624af092525d37c9d516c4>:0 
  at UnityEngine.GUILayout.BeginHorizontal (UnityEngine.GUILayoutOption[] options) [0x0000b] in <fa6f9762ac624af092525d37c9d516c4>:0 
  at KSP_AVC.Toolbar.ToolbarWindow.Window (System.Int32 windowId) [0x00002] in <8584149d963f4e09b44fc3fb1513ee6f>:0 
[LOG 18:48:30.235] KSP-AVC -> System.ArgumentException: Getting control 4's position in a group with only 4 controls when doing repaint`

This seems to suggest KSP_AVC, whatever that is, is the culprit.  Try deleting the KSP_AVC folder seen in this screenshot, it appears to be an unneeded version checker:

https://gyazo.com/6aa57ce23ee94de984157fc3ac4cf0a5

**Comment by Fisheiyy** [comment]
ksp_avc is gone its just spitting out this now 
[EXC 16:51:36.925] NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Components.KopernicusStar.LateUpdate () (at <f093acf4f90f4175b696bc4ddcbb5eb3>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by R-T-B** [comment]
Hmmm.  Can I get the new log to look at?  Maybe this is a bug afterall with how Kopernicus handles additional solar panels or something?  I'd like to try some things in the next build but a log file may give me direction.

In the meantime, removing any additonal parts packs that add solar panels may help...  but that is only a temporary fix.  I think this may need a codeside fix.

**Comment by R-T-B** [comment]
Hmmm.  Can I get the new log to look at?  Maybe this is a bug afterall with how Kopernicus handles additional solar panels or something?  I'd like to try some things in the next build but a log file may give me direction.

In the meantime, removing any additonal parts packs that add solar panels may help...  but that is only a temporary fix.  I think this may need a codeside fix.

**Comment by Fisheiyy** [comment]
i removed the solar panel config because im trying to run just the stock ksp system

**Comment by Fisheiyy** [comment]
[Logs-Kopernicus.zip](https://github.com/R-T-B/Kopernicus/files/5720294/Logs-Kopernicus.zip)

**Comment by R-T-B** [comment]
> i removed the solar panel config because im trying to run just the stock ksp system

Ah.  That rules that out then.  Looking at your logs now.

**Comment by Fisheiyy** [comment]
i know this isnt related to this bug but how do you get into coding the mods for ksp?

**Comment by R-T-B** [comment]
Heh.  Kopernicus was up for adoption (old creator got tired of working on it) and I knew some C# (programming language) so I tried my hand at updating it.  Next thing you know here we are.  I mainly do it because I play the game too, and want Kopernicus to run as bad as most users.

I just got home from work, log was too big for my phone, so I will load/examine it on PC now.

**Comment by R-T-B** [comment]
Ok, I am finally getting somewhere.  What planet pack is this?  It's hanging up on Moho, of all bodies, and I'm curious what it does to it.

**Comment by Fisheiyy** [comment]
> Ok, I am finally getting somewhere. What planet pack is this? It's hanging up on Moho, of all bodies, and I'm curious what it does to it.

no planet pack just stock ksp solar system

**Comment by R-T-B** [comment]
> 
> 
> > Ok, I am finally getting somewhere. What planet pack is this? It's hanging up on Moho, of all bodies, and I'm curious what it does to it.
> 
> no planet pack just stock ksp solar system

Your log indicates it is failing to load some textures for Moho.

`[LOG 11:32:06]: Parsing Target Mods in (Kopernicus.Configuration.PQSLoader) as (System.Collections.Generic.List`1[Kopernicus.Configuration.ModLoader.IModLoader])
[LOG 11:32:06]: Exception Was Recorded: Value cannot be null.
Parameter name: type
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00003] in <ad04dee02e7e4a85a1299c7ee81c79f6>:0 
  at System.Activator.CreateInstance (System.Type type) [0x00000] in <ad04dee02e7e4a85a1299c7ee81c79f6>:0 
  at Kopernicus.ConfigParser.Parser.LoadCollectionMemberFromConfigurationNode (System.Reflection.MemberInfo member, System.Object o, ConfigNode node, System.String configName, System.Boolean getChildren) [0x007c6] in <395892e8bc6a43f7a7ef20a5d37d4d79>:0 
  at Kopernicus.ConfigParser.Parser.LoadObjectFromConfigurationNode (System.Object o, ConfigNode node, System.String configName, System.Boolean getChildren) [0x0014b] in <395892e8bc6a43f7a7ef20a5d37d4d79>:0 
  at Kopernicus.ConfigParser.Parser.LoadObjectMemberFromConfigurationNode (System.Reflection.MemberInfo member, System.Object o, ConfigNode node, System.String configName, System.Boolean getChildren) [0x0030d] in <395892e8bc6a43f7a7ef20a5d37d4d79>:0 
  at Kopernicus.ConfigParser.Parser.LoadObjectFromConfigurationNode (System.Object o, ConfigNode node, System.String configName, System.Boolean getChildren) [0x0015d] in <395892e8bc6a43f7a7ef20a5d37d4d79>:0 
  at Kopernicus.Configuration.Loader.Kopernicus.ConfigParser.Interfaces.IParserEventSubscriber.PostApply (ConfigNode node) [0x000d7] in <f093acf4f90f4175b696bc4ddcbb5eb3>:0 `

I don't know why it thinks that, but it only would do that if Moho is modded incorrectly or otherwise corrupt.

You could try reinstalling your install.  I realize that is awkward for you, but a corrupt install could produce these exact symptoms.  Just remember to not copy the GameData/Squad and SquadExpansion folders when you backup your mods, as they are probably where whatever corrupt file is causing our issue lives.

**Comment by Fisheiyy** [comment]
okay will reinstall and see what it throws at me if it does throw anything

**Comment by Fisheiyy** [comment]
im reinstalling to 1.11 this a bad thing?

**Comment by Fisheiyy** [comment]
just saying i have been using release 50 updating to release 56 and ksp 1.11

**Comment by R-T-B** [comment]
Yeah, not a bad idea.  Keep in mind some other mods might get broke in 1.11 though...  but Kopernicus should not be one of them.

**Comment by Fisheiyy** [comment]
got it

**Comment by Fisheiyy** [comment]
throwing the same error removing solar panel config now

**Comment by R-T-B** [comment]
hmmm...  I just came across a report very similar to yours.  The user was attempting to use Parralax but had not installed both the textures and the dll portion. Maybe this is your issue?

Please ensure if using Parralax, you have the whole mod.  It's two parts.  I will link them:

https://github.com/Gameslinx/Tessellation/releases/download/1.1.1/Parallax.1.1.1.zip
https://github.com/Gameslinx/Tessellation/releases/download/1.1.1/Parallax.-.Stock.Textures.1.1.1.zip

**Comment by Fisheiyy** [comment]
why are they not all in one i thought getting stock textures meant i get the whole mod but its optimized for stock ksp looks like we both had giant brainfarts here but why only moho?

**Comment by Fisheiyy** [comment]
maybe that would also explain why the planets all looked normal and not 8k uhd mega pog

**Comment by Fisheiyy** [comment]
no more screaming and whining from kop thanks for the help

**Comment by R-T-B** [comment]
As for why "only moho" that is curious.  And yes it was sort of a giant brainfart lol.  I guess maybe Moho is just the first planet it loads after Sun?  Would make sense.
